name: Published Release / PreRelease

on:
    release:
        types: [released]
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up OpenJDK 8
              uses: actions/setup-java@v1
              with:
                  java-version: 8.0.232
            - name: Deploy to GitHub Package Registry
              run: mvn -B deploy -P github-actions
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
